Pcodar
uf-mil/mil_common pull request #127
Opened 2018-09-08 18:26 UTC by ironmig

A rebase of #113.

2018-10-20 19:49 UTC, Grymessa requested changes
Just a few things in that label script, possible dead code and old TODOs. Really well made overall and I'd like to see it working on test day tomorrow! On a side note, this would really benefit from a README or more detailed documentation so its quicker to read through and understand what is going on. Just descriptions of the general flow and architecture of this package. As it stands its not too bad to figure out. Just would be a nice thing to have for future members.

2018-10-20 19:49 UTC, Grymestone commented on perception/point_cloud_object_detection_and_recognition/tools/labeling_tool/main.cpp
> +UI Features I want:
Is there going to be a UI or is this just old comments?

2018-10-20 19:49 UTC, Grymestone commented on perception/point_cloud_object_detection_and_recognition/tools/labeling_tool/label_model.hpp
> +// namespace pcod
Dead Code?

2018-10-20 19:49 UTC, Grymestone commented on perception/point_cloud_object_detection_and_recognition/tools/labeling_tool/label_model.cpp
> +  // TODO(tbianchi) Make this a popup thingy
This a feature we need or still want?

2018-10-20 19:49 UTC, Grymestone commented on perception/point_cloud_object_detection_and_recognition/tools/labeling_tool/label_model.cpp
> +#include "main_window.cpp"
So the idea of this file is to label bags with PCODAR clusters so we know what they are in the future? This opens up some interesting possibilities for machine learning down the road. Were there any other plans for this? To use this to label clusters in real time?

2018-10-26 02:27 UTC, kev-the-dev commented
Most of your comments concerned the pointcloud labeling utilities, which I have not modified from the original work by Tess. I've moved this code to deprecated to potentiality be revived later.

The remaining code has been extensively tested. It  does not adequately remove noise for NaviGator's needs (false positives for new objects), but that can be improved with future work. I'd like to merge PCODAR with the current set of features to fix version control dependencies from the other PRs depending on this. 

I have updated the README with detailed description, usage guide, and features TODOs.

2018-10-29 19:35 UTC, Grymessa approved these changes
Sounds good then, thanks for the updates on the README and such.

2018-10-29 19:35 UTC, merged