GREAT INTEGRATION
uf-mil/mil_common pull request #15
Opened 2017-03-28 04:30 UTC by DSsoto

Lets make sure that everything is clean here before we merge back to master.

It would be helpful to have as many people as possible review this.

2017-04-08 22:50 UTC, RustyBamboo commented on perception/mil_vision/great_merge_purgatory/README.txt
> +Some of these files can be made generic and therefore be able to stay as a part of mil_common. Until that is done, they will remain in this folder.
great_merge_purgatory

2017-04-09 01:12 UTC, kev-the-dev requested changes
Could use some work. 6/10

Some of these changes need to be done before merging:

* namespace changes
* anything specific to sub8/navigator

Later
* document

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/include/mil_vision_lib/colorizer/camera_observer.hpp
> +namespace nav{
All namespaces should be ```mil_vision``` for resources in this library.

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/include/mil_vision_lib/colorizer/camera_observer.hpp
> +class CameraObserver
Let's have just one (David's) wrapper for camera subscribers/publishers. @DSsoto can you remove the other ones that do the same thing?

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/include/mil_vision_lib/cv_tools.hpp
> +cv::Mat triangulate_Linear_LS(cv::Mat mat_P_l, cv::Mat mat_P_r,
No documentation for this function. I do I use it/ what does it do? Same with others

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/include/mil_vision_lib/point_cloud_algorithms.hpp
> +class PcdColorizer : public PcdSubPubAlgorithm{
Add TODO comment, mention unfinished

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/include/mil_vision_lib/visualization.hpp
> +  void visualize_buoy(geometry_msgs::Pose &pose, std::string &frame_id);
sub specific, remove

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/object_classification/lidar_to_image.py
> +class LidarToImage(object):
Specific to Navigator, refactor or remove

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/object_classification/object_classification.py
> +from navigator_tools import CvDebug, BagCrawler
Navigator dependency, update to mil_common 

Specific to Navigator, refactor or remove

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/object_classification/roi_generator.py
> +from navigator_tools import BagCrawler
object_classification folder should be removed or refactored to be generic

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/package.xml
> +  <build_depend>navigator_tools</build_depend>
mil_common should not depened on navgiator

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/ros_tools/easy_thresh.py
> +#!/usr/bin/python
Broken for me on kinetic, someone else try to run it

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/ros_tools/on_the_fly_thresholder.py
> +from navigator_tools import image_helpers
use mil_common instead

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/setup.py
> +    packages=[''],
Should this be empty? Can you import the python stuff from this package?

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/src/mil_vision_lib/active_contours.cpp
> +namespace Perturbations
Documentation

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/src/mil_vision_lib/colorizer/camera_observer.cpp
> +CameraObserver::CameraObserver(ros::NodeHandle &nh, std::string &pcd_in_topic, std::string &cam_topic, size_t hist_size)
Document. What does this do?

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/src/mil_vision_lib/colorizer/color_observation.cpp
> +#include <colorizer/color_observation.hpp>
Document the colorizer package. Add a readme

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/src/mil_vision_lib/colorizer/pcd_colorizer.cpp
> +namespace nav{
namespace

2017-04-09 01:12 UTC, kev-the-dev commented on perception/mil_vision/src/mil_vision_lib/cv_utils.cc
> +#include <mil_vision_lib/cv_tools.hpp>
Rename to cpp

Document these functions.

2017-04-09 01:12 UTC, kev-the-dev commented on utils/mil_msgs/CMakeLists.txt
> +add_message_files(FILES
Some of these exist in geometry_msgs/other core ros packages.

2017-04-09 01:12 UTC, kev-the-dev commented on utils/mil_msgs/CMakeLists.txt
> +  MoveTo.action
Is this vehicle dependent?

2017-04-09 01:12 UTC, kev-the-dev commented on utils/mil_msgs/include/mil_msgs/msg_helpers.h
> +namespace uf_common {
namespace

2017-04-09 01:12 UTC, kev-the-dev commented on utils/mil_msgs/include/mil_msgs/msg_helpers.h
> +#pragma once
msg_helpers should be moved to dev tools package. This package should be just message/service/action definitions common to mil projects

2017-04-09 01:12 UTC, kev-the-dev commented on utils/mil_msgs/scripts/param_saver
> +roslib.load_manifest('uf_common')
don't need with catkin. Also these scripts should go to tools package

2017-04-09 01:12 UTC, kev-the-dev commented on utils/mil_tools/include/mil_tools/mil_tools.hpp
> +namespace mil{
rename to mil_tools

2017-04-09 01:12 UTC, kev-the-dev commented on utils/mil_tools/mil_misc_tools/download.py
> +    sub_model_url = "http://goo.gl/f0ennf?gdriveurl"
bad

2017-04-09 01:12 UTC, kev-the-dev commented on utils/mil_tools/mil_ros_tools/bag_crawler.py
> +class BagCrawler(object):
Document

2017-04-09 01:12 UTC, ironmig commented on utils/mil_tools/mil_ros_tools/func_helpers.py
> +    print gooberstein("hello")
wat

2017-04-09 01:12 UTC, ironmig commented on utils/mil_tools/mil_ros_tools/func_helpers.py
> +def add(a, b):
useful

2017-04-09 01:12 UTC, ironmig commented on utils/mil_tools/mil_ros_tools/image_helpers.py
> +def get_parameter_range(parameter_root):
sub specific, remove

2017-04-09 01:12 UTC, ironmig commented on utils/mil_tools/mil_ros_tools/image_helpers.py
> +    def wait_for_camera_info(self, timeout=10):
known bug when time goes backwards, fixed on sub8 version

2017-04-09 01:12 UTC, ironmig commented on utils/mil_tools/mil_ros_tools/msg_helpers.py
> +def rosmsg_to_numpy(rosmsg, keys=None):
@RustyBamboo has some fix for this. Please PR it

2017-04-09 01:12 UTC, ironmig commented on utils/mil_tools/nodes/tf_fudger.py
> +    # This functionality was configured to replace lines in navigator's tf launch file, should refactor to be general later
IF someone wants to refactor to be generic, that'd be cool

2017-04-09 01:12 UTC, ironmig commented on utils/mil_tools/nodes/video_player
> +    rospy.init_node('video_player', anonymous=True)
use argparse instead of params

2017-04-11 05:23 UTC, ironmig commented
Comments addressed and tested (at least for building) with SubjuGator, except for changes mentioned in #30, which can be done in a post-integration repo.

2017-04-11 05:23 UTC, kev-the-dev approved these changes

2017-04-11 05:23 UTC, whispercoros commented
This built on the CI and passed all unit tests except the ros_alarms test that always fails.
-- Your friendly temporary CI guy

2017-04-11 05:24 UTC, merged