Remove .great_purge_purgatory
uf-mil/mil_common pull request #26
Opened 2017-04-10 18:42 UTC by DSsoto

* Removes the great_merge_purgatory in mil_vision
  - Keeps camera_lidar_transformer
  - Code from pinger_finder is removed but then refactored into _passive_sonar_os™_
* camera_stream_demo is moved from the nodes directory to the src dir.

2017-04-10 23:53 UTC, kev-the-dev approved these changes
Good

2017-04-10 23:58 UTC, kev-the-dev requested changes
Check this one thing out

2017-04-10 23:58 UTC, ironmig commented on utils/mil_msgs/srv/CameraToLidarTransform.srv
> +Header header #Stamp of time point was seen for tf
Don't you need to add this service to cmake?

2017-04-11 03:38 UTC, whispercoros commented
This built on the CI and passed all unit tests except the ros_alarms test that always fails.
-- Your friendly temporary CI guy

2017-04-11 03:38 UTC, merged