ML: Adds a labeler script with various tools
uf-mil/mil_common pull request #3
Opened 2017-01-31 03:26 UTC by mattlangford

This is the start of the machine learning framework for use on the sub.
This tool is an easy to use tool for segmenting or labeling images. Right now there are three tools and two so-called image providers (more to come of both!)

**Tools:**
- Paint brush tool: paints the mask like a brush
- Polygon tool: Lets you draw polygons
- Move tool: Lets you move the mask around

**Image Providers:**
- Random color: mostly used for testing
- Webcam: gives you frame by frame access to your webcam

The goal with this is to be an easy to improve framework for segmenting images that will soon be used to train a learned segmenter. The requirements for adding new tools or image providers are fairly straight forward and just require simple adaptions to the current implementation.

2017-02-03 02:24 UTC, kev-the-dev requested changes
Really helpful package. Please add setup.py and the catkin python setup thing so it's rosified

2017-02-03 02:24 UTC, ironmig commented on machine_learning/CMakeLists.txt
> +# catkin_python_setup()
Do you need to uncomment this for python to work?

2017-02-03 02:24 UTC, ironmig commented on machine_learning/labeling/image_providers.py
> +    def get_next_image(self):
might be nice to kwargs this too

2017-02-03 03:21 UTC, mattlangford commented on machine_learning/CMakeLists.txt
> +# catkin_python_setup()
I wasn't planning on exposing any of the inner workings to the system, therefore it wouldn't need to be there.
The image provider class could be helpful externally, but I don't think the machine learning folder is where it should live. Until there's a nice home for it set up (maybe in `mil_dev_tools`), it should stay as a private file only used by the labeler.

2017-02-03 03:22 UTC, mattlangford commented on machine_learning/labeling/image_providers.py
> +    def get_next_image(self):
In reference to the above comment, only the labeler uses this function right now, so no need until it's exposed.

2017-02-11 08:20 UTC, DSsoto requested changes
Requesting either package name change or good reasons not to, plus minor comments, questions.

Also have you considered making this a qt app?

2017-02-11 08:20 UTC, DSsoto commented on machine_learning/CMakeLists.txt
> +)
Can you remove commented out boilerplate?

2017-02-11 08:20 UTC, DSsoto commented on machine_learning/labeling/image_providers.py
> +    name = "Random Color Generator"
I'm not seeing this being used anywhere, should it be a comment?

2017-02-11 08:20 UTC, DSsoto commented on machine_learning/labeling/labeler.py
> +'''
Is this a docstring for the whole labeler.py module?

2017-02-11 08:20 UTC, DSsoto commented on machine_learning/labeling/labeler.py
> +        if len(tools) == 0:
Like what you did there.

2017-02-11 08:20 UTC, DSsoto commented on machine_learning/package.xml
> +  <name>machine_learning</name>
I think that just like with sub and boat, we should establish a  mil namespace. I propose that all packages in this repo start with `mil_`. What say you?

2017-02-11 14:04 UTC, mattlangford commented on machine_learning/package.xml
> +  <name>machine_learning</name>
Sure

2017-02-11 14:05 UTC, mattlangford commented on machine_learning/CMakeLists.txt
> +)
I like to leave in the lines that could possibly be used in the future, that way if someone adds a c++ file or wants messages, they can just uncomment the lines rather then going to some other cmake file and copying what they need

2017-02-11 14:07 UTC, mattlangford commented on machine_learning/labeling/image_providers.py
> +    name = "Random Color Generator"
Line 212 in the `labeler.py` file

2017-02-11 14:07 UTC, mattlangford commented on machine_learning/labeling/labeler.py
> +'''
I suppose it is

2017-03-09 07:41 UTC, DSsoto approved these changes

2017-03-09 07:42 UTC, DSsoto commented
This is ready to merge but shouln't be until **__The Great Merge__** is complete and this is rebased on top of it.

2017-04-08 15:56 UTC, mattlangford commented
Going to close based on some stuff. This'll still exist in my branch if we ever want it.

2017-04-08 15:56 UTC, closed without merging

2017-04-08 16:58 UTC, DSsoto commented
Wait how come? This seems like pretty useful stuff. I just wanted to wait until the great merge was done since this is lower priority.

2017-04-08 17:19 UTC, mattlangford commented
@tessbianchi made some pretty compelling arguments to me about using an online labeling tool and adding infra to support that rather then rolling our own. The benefits of the online tool are too many to type so next time there is a call we can discuss.

2017-04-08 21:02 UTC, DSsoto commented
Oh yea, she talked to me about that too. Fair enough.