GNC: Absorb the odometry_tools repository
uf-mil/mil_common pull request #37
Opened 2017-04-14 09:17 UTC by whispercoros

I decided to pull request this due to lack of input on uf-mil/odometry_tools#4. I still think we should wait for input before merging, but no longer than a week.

The odometry_tools repository currently has dependencies on mil_common, but should be compilable on it's own. Since this is a package that is common to both active robots and is not a separate package we are planning on integrating, it makes sense to simple absorb it into mil_common. I preserved all of the history from that repository and moved both packages into a `gnc` directory to match the root directory conventions of SubjuGator.

2017-04-14 09:23 UTC, whispercoros commented
If this is merged, we should move the odometry_tools package to uf-mil-archive.

2017-04-14 09:38 UTC, forrestv commented
Fine by me. However, note that odom_estimator is only used on the sub, so
maybe it should be in the sub repo instead (leaving only odometry_utils in
mil_common)?

On Apr 14, 2017 05:23, "Anthony Olive" <notifications@github.com> wrote:

> If this is merged, we should move the odometry_tools package to
> uf-mil-archive.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/uf-mil/mil_common/pull/37#issuecomment-294123770>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AADp4JT7afZj7zr_Nr9rnsioVt4mceLfks5rvzslgaJpZM4M9mG1>
> .
>

2017-04-14 16:51 UTC, kev-the-dev approved these changes
This package could use some work on the documentation and convention front (not even a README!), but I think it makes since to absorb this as it has mil_common dependencies. Long live the reign of mil common! May we conquer all!

2017-04-14 16:51 UTC, ironmig commented on gnc/odom_estimator/CMakeLists.txt
> +add_executable(test_unscented_transform src/test_unscented_transform.cpp)
Tests should be through rostest, using python unittest or gtest.

2017-04-14 20:52 UTC, whispercoros commented
Good point, odom_estimator seems SubjuGator specific in that it would have to be changed a bit to work with other projects. I'm in favor of moving that to SUbjuGator's `gnc` directory. Any objections?

2017-04-14 20:55 UTC, DSsoto commented
Also in favor of adding it to Sub gnc

2017-04-14 20:56 UTC, DSsoto requested changes
Also in favor of moving odom_estimator to SubjuGator gnc.

2017-04-16 03:26 UTC, ironmig commented
if you can some how git your way into this I think it is best:

* odometry_tools/odom_estimator is put into SubjuGator gnc folder with history intact
* odometry_tools/odom_utils is put into mil_common with history preserved
* Necessary changes to CMakelist/package.xml is made in each so it builds
* odometry_tools is archived

2017-04-16 12:32 UTC, whispercoros commented
Looking through the code a bit, odometry_utils depends on odom_estimator. Have a look at `odometry_utils/src/transform_odometry.cpp`, which contains the fairly clear line:

    using namespace odom_estimator;

Unless these can be easily separated, it makes sense to just keep them together.

2017-04-18 02:42 UTC, ironmig commented
Yeah I say just move it to Sub8.

2017-04-18 13:02 UTC, whispercoros commented
@DSsoto, are you in favor of keeping this here or moving it to SubjuGator?

2017-04-18 17:18 UTC, DSsoto commented
It seems best to just add to SubjuGator and later see if it can be made generic and added to mil_common.

2017-04-18 17:22 UTC, forrestv commented
NaviGator uses odometry_tools, though... so the only current option would
be adding both to mil_common, right?

I can reverse the dependency pretty easily, letting odometry_tools be put
in mil_common and odom_estimator in SubjuGator.

On Apr 18, 2017 13:18, "David Santiago Soto" <notifications@github.com>
wrote:

> It seems best to just add to SubjuGator and later see if it can be made
> generic and added to mil_common.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/uf-mil/mil_common/pull/37#issuecomment-294916203>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AADp4DdyU0hSAdi6D2Y-XEGANRYDPTH7ks5rxPB8gaJpZM4M9mG1>
> .
>

2017-04-18 17:26 UTC, DSsoto commented
@forrestv if you want to do that, that would be great

2017-04-18 20:40 UTC, forrestv commented
Hmm, looking at it, it would require moving a lot of the odom_estimator code over ... I think we should just take the easy route (move both into mil_common) rather than doing that right now.

2017-04-18 21:16 UTC, DSsoto approved these changes

2017-04-18 21:29 UTC, merged