CLEANUP: Organize online_bagger
uf-mil/mil_common pull request #45
Opened 2017-04-24 01:43 UTC by kingkevlar

I organized online_bagger to match the existing file structure in mil_common and made the necessary (one line) change to the actual file (online_bagger.py) required from moving the .srv file from mil_tools to mil_msgs (with the rest of the msgs and srvs).

2017-04-24 02:09 UTC, mattlangford approved these changes
A suggestion for organization, take it or leave it

2017-04-24 02:09 UTC, mattlangford commented on utils/mil_tools/mil_ros_tools/online_bagger/config/online_bagger_example.yaml
> -# list an arbitrary set of topics to  subscribe to and stream:
I think this is useful to keep as an example in an example launch.
Idea:
Move `online_bagger.py` into `utils/mil_tools/nodes`, then making a `utils/mil_tools/launch` where you put the launch file with the config in there as params in the launch.

2017-04-24 16:26 UTC, kingkevlar commented on utils/mil_tools/mil_ros_tools/online_bagger/config/online_bagger_example.yaml
> -# list an arbitrary set of topics to  subscribe to and stream:
Give me two more lines

2017-04-24 18:12 UTC, sentree requested changes
This will not work as it is. In order to build the message in the mil_msgs package, you need to add `BaggerCommands.srv` to the `add_service_files` block in `utils/mil_msgs/CMakeLists.txt`.

2017-04-24 22:05 UTC, kev-the-dev requested changes
The example launch file now refers to a config file that isn't there. Should change before merging

2017-04-24 22:36 UTC, whispercoros commented
Is there a reason we're keeping the sample launch file and not the sample configuration file? Realistically, I think both of these should be in a readme with some good documentation.

    @kingkevlar --verbose

2017-04-24 22:40 UTC, kev-the-dev approved these changes

2017-04-24 22:44 UTC, kingkevlar commented
@whispercoros It should be there now (both the config and launch file)

2017-04-25 22:07 UTC, sentree approved these changes

2017-04-25 22:07 UTC, merged