ONLINE BAGGER: changes to allow integration with mil's bag command
uf-mil/mil_common pull request #48
Opened 2017-04-30 00:10 UTC by ironmig

* add much more configurability to where bags are placed from service call. Can now specify directory, will add .bag if not present, resolve relative directories, etc

* add topics arugment to service. If not empty string, only space seperated list topics will be bagged

* read BAG_ALWAYS and bag_* environment variables to get topics to buffer from bmux

2017-04-30 06:10 UTC, sentree requested changes
I like what you've done with the place. Nice signed commits! A couple of suggestions, though.

2017-04-30 06:10 UTC, sentree commented on utils/mil_msgs/srv/BaggerCommands.srv
> +#  camera_tests/test1.bag -> /bag_package_path/test1.bag
Shouldn't the result be a bag in `<bag_package_path>/camera_tests/test1.bag`? Also, I would perfer that there be some kind of marker that this is a variable (i.e. the <> in my example here or something else).

2017-04-30 06:10 UTC, sentree commented on utils/mil_tools/nodes/online_bagger.py
> +        # Merge rosparam topics with enviroment variable topics used by bmux
I recommend changing all instances of `bmux` to `bag`. Our old friend `bmux` is on the way out.

2017-04-30 06:10 UTC, sentree commented on utils/mil_tools/nodes/online_bagger.py
> +            add_env_var(os.environ['BAG_ALWAYS'])
This whole section is gold; you write a mean Python, my friend.

2017-04-30 06:10 UTC, whispercoros commented on utils/mil_tools/nodes/online_bagger.py
> +            if len(selected_topics) > 0 and not topic[0] in selected_topics:
Nice one-lining.

2017-04-30 06:10 UTC, whispercoros commented on utils/mil_tools/nodes/online_bagger.py
> +        bag_dir = os.path.join(self.dir, bag_dir)
This will not work with an absolute path. Is that intentional?

2017-04-30 06:10 UTC, whispercoros commented on utils/mil_tools/nodes/online_bagger.py
> +        self.dir = rospy.get_param(rospy.get_name() + '/bag_package_path', default=os.environ['HOME'])
This should probably default to a dated folder under the directory specified in the `BAG_DIR` environment variable if it exists.

2017-04-30 21:17 UTC, ironmig commented on utils/mil_tools/nodes/online_bagger.py
> +        bag_dir = os.path.join(self.dir, bag_dir)
os.path.join does actually work here.
```
from os import path
path.join("/home/example/", "/home/bob/my_bag_folder/")
-> '/home/bob/my_bag_folder/'
```

2017-04-30 21:24 UTC, ironmig commented on utils/mil_msgs/srv/BaggerCommands.srv
> +#  camera_tests/test1.bag -> /bag_package_path/test1.bag
You're right. This is how it behaves, the comment is incorrect.

2017-04-30 22:14 UTC, mattlangford approved these changes
The next big change is to c++!

2017-04-30 22:14 UTC, mattlangford commented on utils/mil_tools/nodes/online_bagger.py
> +        self.dir = rospy.get_param(rospy.get_name() + '/bag_package_path', default=None)
Can't you format the name in such a way that it's based on the parent node name? `~/my_param` or `my_param` or something?

2017-04-30 22:14 UTC, mattlangford commented on utils/mil_tools/nodes/online_bagger.py
> +        if bag_name.rfind('.bag')-len(bag_name) != -4:
`bag_name[-4:] != '.bag'`

2017-04-30 22:14 UTC, mattlangford commented on utils/mil_tools/nodes/online_bagger.py
> +                    self.subscriber_list[i] = (topic[0], topic[1], True)
If it's easy, could you make this a dictionary? After an argument or two long lists used to store dictionary like data can be confusing.

2017-04-30 22:14 UTC, mattlangford commented on utils/mil_tools/nodes/online_bagger.py
> +    def _get_default_filename(self):
Request to make the default filename `hi_im_dumb_and_didnt_name_my_bag_<date>`

2017-04-30 23:01 UTC, ironmig commented on utils/mil_tools/nodes/online_bagger.py
> +        if bag_name.rfind('.bag')-len(bag_name) != -4:
you're a wizard

2017-04-30 23:03 UTC, ironmig commented on utils/mil_tools/nodes/online_bagger.py
> +                    self.subscriber_list[i] = (topic[0], topic[1], True)
Yeah that would make things easier, [can do](https://www.youtube.com/watch?v=y9IcGZZnC1k)

2017-04-30 23:05 UTC, whispercoros commented on utils/mil_tools/nodes/online_bagger.py
> +        bag_dir = os.path.join(self.dir, bag_dir)
Wow, smart library

2017-04-30 23:07 UTC, ironmig commented on utils/mil_tools/nodes/online_bagger.py
> +        self.dir = rospy.get_param(rospy.get_name() + '/bag_package_path', default=None)
Yeah its ```rospy.get_param('~my_param')```, will do

2017-04-30 23:38 UTC, ironmig commented
Think I got it all folks

2017-05-01 00:13 UTC, whispercoros commented on utils/mil_tools/nodes/online_bagger.py
> +        self.dir = rospy.get_param('~bag_package_path', default=None)
Just wondering if you still wanted to have this default to a dated folder under the directory specified in the BAG_DIR environment variable if it exists. You added a thumbs up to the comment, so I think you just missed it when making changes.

2017-05-01 01:59 UTC, ironmig commented on utils/mil_tools/nodes/online_bagger.py
> +        self.dir = rospy.get_param('~bag_package_path', default=None)
Alright I check for that environ variable if the ros param is not set

2017-05-01 05:07 UTC, whispercoros commented on utils/mil_tools/nodes/online_bagger.py
> +        self.dir = rospy.get_param('~bag_package_path', default=None)
Awesome, thanks!

2017-05-01 05:07 UTC, sentree approved these changes

2017-05-01 05:07 UTC, merged