SCRIPTS: Bag OS (ɔ)
uf-mil/mil_common pull request #49
Opened 2017-04-30 07:07 UTC by whispercoros

Preface: Note the copyleft, for open source software *(Ahem, #17)*

These changes should complete work on the bagging system for the mote part. They are dependent on #48 and uf-mil/SubjuGator#228. To brieefly summarize what has been done:

* The `bmux` command has been merged into the `bag` command in the form of a `-i` flag. This means that `bag -i <project_repository_name>` should replace `bmux <project_repository_name>` in the Bash runcom file on all of the vehicles.
* A `-e` flag has been added to export configurations to a file. This means that new groupings created with the `-g` flag can easily be saved.
* A `-t` flag was added to trigger a note taking mode after the bag has been saved. It will open a text file in the same directory as the bag file and with the same name in Vim. Hopefully this makes it easier to grep through the bag directories at a later date to find what we need.
* Support for the online bagger was added with the `-o` flag. Passing this along with <time> will trigger the dumping of a bag containing the desired topics that begins at t - <time>.

Everything here except the interaction with the online bagger has been tested and works well. Double check my syntax on the `rosservice` command, but I believe it is correct.

2017-04-30 23:57 UTC, kev-the-dev requested changes
As #48 is implemented right now, you must pass the full directory in to the bag name to ensure it gets in the right place. Once thats done we gud

2017-04-30 23:57 UTC, ironmig commented on scripts/bag.sh
> +				echo "-o [TIME]	--online		Bag a number of seconds in the past"
Is this going to be misaligned with the rest of the help text?

2017-04-30 23:57 UTC, ironmig commented on scripts/bag.sh
> +		rosservice call /online_bagger/dump "{bag_name: '$NAME', topics: '$TOPICS', bag_time: '$TIME'}"
You should pass in the full path here.
 ```rosservice call /online_bagger/dump "{bag_name: '$BAG_DIR/$(date +%Y-%m-%d)/$NAME', topics: '$TOPICS', bag_time: '$TIME'}"``` should work

2017-04-30 23:57 UTC, ironmig commented on scripts/bmux.sh
> -#!/bin/bash
It is always a sad day when we lose a *mux script, but alas we must move on.

2017-05-01 00:15 UTC, whispercoros commented on scripts/bag.sh
> +				echo "-o [TIME]	--online		Bag a number of seconds in the past"
Nope. Don't question it, it's the tab lifestyle...

2017-05-01 00:16 UTC, whispercoros commented on scripts/bmux.sh
> -#!/bin/bash
I'm sure one will spring up soon to replace it.

2017-05-01 05:14 UTC, whispercoros commented
The points that @ironmig made have been addressed.

2017-05-01 07:21 UTC, DSsoto approved these changes
This is pretty good Tony, hope you will soon produce equally good mission/perception code.

2017-05-01 07:21 UTC, DSsoto commented on scripts/bag.sh
> +	echo "# diliniated list of ROS topics. The only two exceptions to this rule are the"
deliniated

2017-05-01 14:02 UTC, whispercoros commented
The points that @dsoto made have been addressed.

2017-05-01 15:16 UTC, DSsoto commented
Good to merge when @ironmig updates review.

2017-05-01 16:06 UTC, kev-the-dev approved these changes

2017-05-01 21:12 UTC, merged