TOOLS: improve labelme and fix_bag scripts
uf-mil/mil_common pull request #52
Opened 2017-05-13 00:21 UTC by ironmig

* Improve label me bag interface. Each segment can now contain multiple image topics (ex: stereo) and will produce its own bag (rather than one bag for every segment produced from the same input bag)
* fix bag has a few new options, including specifying timestamps to crop a bag and a list of topics to either include or ignore in the output bag

I tested the labelme script with the bags in the path marker and it worked well. I gave it a YAML, ran the script, and the images showed up on my LabelMe server. After I finished labeling, I ran it with the ```-i``` flag and it produced a bag for each segment containing the original data and the labels.

2017-05-13 15:39 UTC, DSsoto approved these changes
Good work man, this is pretty useful.

2017-05-13 15:39 UTC, DSsoto commented on utils/mil_tools/mil_ros_tools/label_me_bag.py
> +                  self.config['bags'][i]['segments'][j]['topics'] = [self.config['bags'][i]['segments'][j]['topics']]
Why not:
```python
segment = [segment]
```
Does that not work?

2017-05-14 23:31 UTC, DSsoto commented
Will wait for @whispercoros's review before merging.

2017-05-17 15:04 UTC, kev-the-dev commented on perception/mil_vision/mil_vision_tools/rect_finder.py
> +                dist_coeffs = distortionCoeffs()
Oops should be ```cam.distortionCoeffs()```

2017-05-18 14:18 UTC, DSsoto requested changes
This looks good. How was this tested? Requesting some usage documentation for the labeled bag tester before merging.

2017-05-18 14:18 UTC, DSsoto commented on utils/mil_tools/mil_ros_tools/labeled_bag_tester.py
> +            dx = time.time() - x
Why not use rostime? This prevents you from running this at different bag playback speeds.

2017-05-22 15:27 UTC, ironmig commented
I'm getting rid of labeled_bag_tester in this PR as it's still WIP and I'd rather get the other stuff merged in the meantime. The rect_finder was tested by replacing the relevant parts of path_marker_finder in subjugator (which will be PRed once this is merged).

2017-05-22 20:35 UTC, DSsoto approved these changes
Dude great work with RectFinder! Thats some good code. Oooohwieeee!

The bag stuff is good too. Next time, I would make these kind of things separate PR's though.

Let me know if you want me to merge or you want to take my more robust quadrilateral approximation suggestion.

2017-05-22 20:35 UTC, DSsoto commented on perception/mil_vision/mil_vision_tools/rect_finder.py
> +    def sort_corners(rect, debug_image=None):
Thanks for doing this! Good work!

2017-05-22 20:35 UTC, DSsoto commented on perception/mil_vision/mil_vision_tools/rect_finder.py
> +    def get_corners(self, contour, epsilon_factor=0.02, debug_image=None):
One way I reliably approximated contours as quadrilaterals was by doing it iteratively and increasing epsilon until I had a quadrilateral. Its more robust for when over-saturation or caustics make it hard to retrieve the quadrilateral. 

Check [this](https://github.com/uf-mil/SubjuGator/blob/5d169e9d23d6b20ef488040257fc0837ac887adb/perception/sub8_perception/nodes/torpedo_board.cpp#L1095) out for an implementation.

2017-05-22 20:35 UTC, DSsoto commented on perception/mil_vision/mil_vision_tools/rect_finder.py
> +        Uses the model of the object, the corosponding pixels in the image, and camera
`corresponding`

2017-05-22 20:35 UTC, DSsoto commented on perception/mil_vision/mil_vision_tools/rect_finder.py
> +        vector = vector/np.linalg.norm(vector)
This will fail flake8 checks soon.

2017-05-22 21:11 UTC, ironmig commented on perception/mil_vision/mil_vision_tools/rect_finder.py
> +    def get_corners(self, contour, epsilon_factor=0.02, debug_image=None):
Yeah I was having problems with that, great idea! I'll implement that in a future PR.

2017-05-22 21:44 UTC, ironmig commented on perception/mil_vision/mil_vision_tools/rect_finder.py
> +        vector = vector/np.linalg.norm(vector)
I corrected all the issues outputted by flake8 in all the files changed in this PR

2017-05-22 22:47 UTC, merged