SCRIPTS: Add management features to wsmux
uf-mil/mil_common pull request #54
Opened 2017-05-15 14:35 UTC by whispercoros

This implements the functionality requested in uf-mil/SubjuGator#239. It also adds the functionality to bind to the current workspace if none is passed with the `-b` argument and the ability to unbind an SSH client with the `-u` argument.

2017-05-16 01:01 UTC, kev-the-dev requested changes
I ain't no bash boi but I don't think this will have the desired behavior.

2017-05-16 01:01 UTC, ironmig commented on scripts/wsmux.sh
> +							if $(git diff-index --quiet HEAD --); then
So is this checking for the exit code? Looks like this command returns exit code 1 for an unclean working directory. So isn't this the opposite of what you want (assuming if runs for positive exit codes)

2017-05-16 01:01 UTC, ironmig commented on scripts/wsmux.sh
> +								git checkout -B master upstream/master
Be sure to handle submodules. I think ```git submodule update``` will do it.

2017-05-16 04:44 UTC, whispercoros commented on scripts/wsmux.sh
> +							if $(git diff-index --quiet HEAD --); then
In bash, an exit code of 0 will be taken as `true` for an if statement. So if the working directory is clean, the command will return 0 and the update will proceed.

2017-05-16 04:45 UTC, whispercoros commented on scripts/wsmux.sh
> +								git checkout -B master upstream/master
Are you sure that won't update them to the latest version of their origin repository?

2017-05-16 23:58 UTC, whispercoros commented on scripts/wsmux.sh
> +								git checkout -B master upstream/master
This has been added and tested.

2017-05-17 00:02 UTC, kev-the-dev approved these changes

2017-05-17 00:07 UTC, DSsoto approved these changes

2017-05-17 00:34 UTC, merged