BUG: fix small bugs in mil_vision and mil_ros_tools
uf-mil/mil_common pull request #60
Opened 2017-05-23 20:32 UTC by ironmig

Found some bugs running old code. Fixed em' #twolinediff

* in the easy_thresh script, use a different function for BoxPoints if on opencv3

* fix some import nonsense in geometry_helpers

2017-05-23 22:14 UTC, DSsoto requested changes
I don't really think this is the best way to deal with these, but good on you for trying to clean up old bugs. Awaiting responses.

2017-05-23 22:14 UTC, DSsoto commented on utils/mil_tools/mil_ros_tools/geometry_helpers.py
> +from tf.transformations import quaternion_matrix as tf_quaternion_matrix
We don't really have these style of imports in our codebase. I think consistency is nice. if you just do `import tf.transformations as trans` then you could just do `trans.quaternion_multiply()`. That way it's clear that all of these share the same namespace.

2017-05-23 22:14 UTC, DSsoto commented on perception/mil_vision/ros_tools/easy_thresh.py
> +            box = cv2.boxPoints(rect)
No need to support multiple versions. The rest of our code is just compatible with Opencv3 (which this doesn't even check for).

2017-05-25 03:38 UTC, DSsoto approved these changes

2017-05-25 03:48 UTC, DSsoto commented
Can you squash the commits? For single commit PRs, requested changes should be ammended to the original commit as per the [code policy](https://github.com/uf-mil/mil_common/wiki/Code-Policy#review-proces).

Also, in the future, consider just appending innocuous little changes like these to existing PR's so we don't muddy the history too much with unnecessary merge commits.

2017-05-25 22:21 UTC, ironmig commented
Squashed 'em. If you don't like merge commits you can always click rebase instead. I think I'd rather small bug fix PRs be filed than to put these changes in unrelated PRs that might take much longer to get merged.

2017-05-26 16:21 UTC, merged