pythonFinder and Pep8 checker: Automatic run on PR, modified jenkins …
uf-mil/mil_common pull request #99
Opened 2018-02-07 15:51 UTC by brooksturtle

Jenkins file creates warning if any pep8 errors.

2018-02-07 15:55 UTC, RustyBamboo commented on utils/mil_tools/scripts/ReadMe.txt
> +sProgramFinder:
Looks like you got a typo.
Also, you can use markdown to make the readme look nicer.
Convientially the file name should be ```readme.md``` or ```README.md```

2018-02-07 18:25 UTC, kev-the-dev requested changes

2018-02-07 18:25 UTC, ironmig commented on utils/mil_tools/scripts/pythonFinder.py
> +            break
This block should be refactored. You only need to check the FIRST line of each program.

2018-02-07 18:25 UTC, ironmig commented on utils/mil_tools/scripts/pythonFinder.py
> +for program in allFileList:
You can also check if the file ends in .py in this loop so you don't need to worry about double entries

2018-02-07 18:25 UTC, ironmig commented on utils/mil_tools/scripts/pythonFinder.py
> +    if '.py' in program and '.pyc' not in program:
Don't need .pyc

2018-02-07 18:26 UTC, kev-the-dev requested changes

2018-02-07 18:26 UTC, ironmig commented on utils/mil_tools/scripts/pythonFinder.py
> +for program in finalList:
This should ideally be just ONE command which runs, checking all files by adding each as an argument.

2018-02-16 20:04 UTC, ironmig commented
I'm going to have someone else finish this on Monday if it has not been updated.

2018-02-28 22:58 UTC, ironmig commented
Checkout #103 to see a simpler and more efficient implementation.

2018-02-28 22:58 UTC, closed without merging